<a href="https://colab.research.google.com/github/JoshPardosi-231401031/Python-Data-Cleaning-Project/blob/main/Project_DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [101]:
!pip install ydata-profiling pandas numpy -q

In [102]:
import pandas as pd
import numpy as np
from ydata_profiling import ProfileReport
from google.colab import files

In [103]:
uploaded = files.upload()

Saving messy_customer_orders.csv to messy_customer_orders (1).csv

In [104]:
df = pd.read_csv('messy_customer_orders.csv')

In [105]:
profile = ProfileReport(df, title='Profiling Report', explorative=True)
profile.to_file('report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]
  8%|▊         | 1/12 [00:00<00:07,  1.41it/s]
 17%|█▋        | 2/12 [00:00<00:04,  2.41it/s]
100%|██████████| 12/12 [00:11<00:00,  1.03it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [106]:
# Jumlah Baris dan Kolom
print('data size:', df.shape )

data size: (51000, 12)

In [107]:
df.dtypes

order_id           object
customer_id        object
order_date         object
country            object
category           object
product            object
quantity            int64
unit_price         object
total_amount      float64
status             object
payment_method     object
is_returned        object
dtype: object

In [108]:
print(f'\nData Kosong:\n{df.isnull().sum()}')

Data Kosong:
order_id             0
customer_id       2033
order_date           0
country           2540
category          3052
product              0
quantity             0
unit_price        2033
total_amount      1528
status               0
payment_method       0
is_returned          0
dtype: int64

In [109]:
df.head()

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
0,ORD-004208,CUST-6426,22/07/2022,canada,Clothing,Notebook Set,4,38.57,154.28,Shipped,PayPal,TRUE
1,ORD-006584,NaN,10-12-2023,NaN,NaN,Backpack,-2,NaN,NaN,Shipped,Cash,True
2,ORD-013539,NaN,26/07/2023,NaN,NaN,Travel Mug,9,NaN,NaN,Delivered,PayPal,1
3,ORD-038448,CUST-2286,02-18-2022,Germany,clothing,Bluetooth Speaker,2,192.93,385.86,shipped,Cash,No
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.7,446.80,pending,Bank Transfer,Y

In [110]:
# Standarize Columns names in one line
df.columns = df.columns.str.replace(' ', '_').str.lower().str.strip()
print(df.columns)

Index(['order_id', 'customer_id', 'order_date', 'country', 'category',
       'product', 'quantity', 'unit_price', 'total_amount', 'status',
       'payment_method', 'is_returned'],
      dtype='object')

In [111]:
# Check percentage missing value
missing = df.isnull().mean()*100
print(missing[missing > 0].sort_values(ascending = True))

total_amount    2.996078
customer_id     3.986275
unit_price      3.986275
country         4.980392
category        5.984314
dtype: float64

In [112]:
# how to handle missing value systematically

# drop duplicates rows
df = df.drop_duplicates()
# fill missing numbers with median
df['total_amount'] = df['total_amount'].fillna(df['total_amount'].median())
# fill mising text with 'unknown'
categorical_cols = ['customer_id', 'country', 'category']
for col in categorical_cols:
  df[col] = df[col].fillna('unknown')
# Check The remaining Missing Values
print(df.isnull().sum())

order_id             0
customer_id          0
order_date           0
country              0
category             0
product              0
quantity             0
unit_price        2000
total_amount         0
status               0
payment_method       0
is_returned          0
dtype: int64

/tmp/ipykernel_7429/2132759823.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_amount'] = df['total_amount'].fillna(df['total_amount'].median())
/tmp/ipykernel_7429/2132759823.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].fillna('unknown')

In [113]:
# standarized text with mapping dictionary

# 1 change text to lowercase and no extraspace
cols_to_clean =['category', 'status', 'country']
for col in cols_to_clean:
  df[col] = df[col].astype(str).str.strip().str.lower()

# 2 fix the wrong text
country_map = {
    'u.s.a': 'usa',
    'united states' : 'usa',
    'us' : 'usa',
    'd' : 'germany',
    'de' : 'germany',
    'united kingdom' : 'uk',
    'u.k.' : 'uk',
    'aus' : 'australia'
}
# apply dict to country cols
df['country'] = df['country'].map(country_map).fillna(df['country'])
# print
print(df['country'].value_counts())

/tmp/ipykernel_7429/460793797.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.lower()
/tmp/ipykernel_7429/460793797.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.lower()

country
usa          11962
germany       9055
australia     8851
canada        8835
uk            8797
unknown       2500
Name: count, dtype: int64

/tmp/ipykernel_7429/460793797.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.lower()
/tmp/ipykernel_7429/460793797.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'] = df['country'].map(country_map).fillna(df['country'])

In [114]:
# fix and extract the order_date
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

# extract useful time features into new columns
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_day_of_week'] = df['order_date'].dt.day_name()

print(df[['order_date', 'order_year', 'order_month', 'order_day_of_week']].head())

/tmp/ipykernel_7429/1981476605.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')
/tmp/ipykernel_7429/1981476605.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

  order_date  order_year  order_month order_day_of_week
0 2022-07-22      2022.0          7.0            Friday
1        NaT         NaN          NaN               NaN
2 2023-07-26      2023.0          7.0         Wednesday
3        NaT         NaN          NaN               NaN
4 2024-06-18      2024.0          6.0           Tuesday

/tmp/ipykernel_7429/1981476605.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_year'] = df['order_date'].dt.year
/tmp/ipykernel_7429/1981476605.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_month'] = df['order_date'].dt.month
/tmp/ipykernel_7429/1981476605.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_day_of_week'] = df['order_date'].dt.day_name()

In [115]:
# make filter for impossible order quantity
impossible_order_quantity = df['quantity'] <= 0
# check the missing rows
print(df.loc[impossible_order_quantity, ['order_id', 'product', 'quantity', 'unit_price', 'total_amount']])

         order_id              product  quantity unit_price  total_amount
1      ORD-006584             Backpack        -2        NaN       690.105
193    ORD-040428     Resistance Bands         0    $258.43         0.000
306    ORD-029737             Yoga Mat        -3        NaN       690.105
449    ORD-049440           Phone Case         0  $1,212.28         0.000
638    ORD-013603             Yoga Mat         0     110.68         0.000
...           ...                  ...       ...        ...           ...
50364  ORD-021365     LED Strip Lights         0  $1,264.40         0.000
50446  ORD-032321           Sunglasses        -3     179.77      -539.310
50576  ORD-025548  Mechanical Keyboard        -4      18.39       -73.560
50695  ORD-038361           Phone Case        -1    $213.67      -213.670
50923  ORD-033764        Monitor Stand         0     256.47         0.000

[500 rows x 5 columns]

In [116]:
# make a new clean csv
df.to_csv('cleaned_customer_orders.csv', index=False)
# import files
from google.colab import files
files.download('cleaned_customer_orders.csv')